### ISSUE TITLE
Handle outlook.office.com

### ISSUE THREAD

**Issue by epa** [wtimme/firefox-remove-safelinks#3]
The Microsoft Outlook web application generates safelinks of the form
`https://outlook.office.com/mail/safelink.html?url=MYURL&corid=349b3f64-9f28-8f52-5aec-254b298bdc8d`
The corid parameter appears new, until recently it passed only the url parameter.
Anyway, could the extensions also handle these?

**Comment by wtimme** [comment]
Thanks for the suggestion! Since you provided an example, I was able to add support for outlook.office.com.

The new version of the add-on (1.2.0) is currently awaiting review by the Firefox Add-on team.

**Comment by wtimme** [comment]
Version 1.3.0 has been approved and is now available. Let me know if that works for you.
