### ISSUE TITLE
Request additional safelink URL

### ISSUE THREAD

**Issue by dylan-klomparens** [wtimme/firefox-remove-safelinks#8]
Hello! Thank you for producing this wonderful add-on! Could I request the addition of another base-URLs for code in background.js?

https://\*.safelinks.protection.office365.us/\*

The above URL is the wildcard version of these two servers...
https://usg01.safelinks.protection.office365.us/
https://usg02.safelinks.protection.office365.us/

**Comment by wtimme** [comment]
Thank you very much for the suggestion and for the feedback, @dylan-klomparens! I have incorporated the new domain into the addon and uploaded a new build to the Firefox Addon directory for review.

**Comment by wtimme** [comment]
I am happy to report that version 1.6.0 with the new URL has made it through the Firefox Addon Review process. Thanks again for your suggestion!
