### ISSUE TITLE
Addon Status after install: Cant_read_and_change_data_on_this_site

### ISSUE THREAD

**Issue by ghost** [wtimme/firefox-remove-safelinks#9]
After installing addon version 1.6.0 on Firefox 115.9.1esr on Debian 5.10.209-2  the status of the add-on remains "Can't read and change data on this site", for all sites including Microsoft safelink sites. See picture

![Cant_read_and_change_data_on_this_site_safelink](https://github.com/wtimme/firefox-remove-safelinks/assets/14205686/f03ce29a-80e6-424f-b710-db61392213ba)

redirects still go via Microsoft "safe" links.

Also tested on Firefox 124.0.1 on Windows 10, same result.

**Comment by ghost** [comment]
error not reproducible, not sure what was the issue yesterday. Works now :)

**Comment by arichtman-srt** [comment]
I have this too - it just stays greyed out and not working :'(
